version: '3.1'
services:
  ubuntu:
    image: ubuntu:latest
    container_name: efimov_5
    command: touch /test/change_me.txt
    volumes:
      - ${PWD}/:/test
  
  ubuntu_2:
    image: ubuntu:latest
    container_name: efimov_6
    command: chmod 777 /test/change_me.txt
    volumes:
      - ${PWD}/:/test
    depends_on:
      - ubuntu  
